language: node_js

cache: yarn

node_js:
- node

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"

script:
- npm run flow
- npm run test:coverage
- npm run build
